### ISSUE TITLE
Include All, Exclude All buttons don't work

### ISSUE THREAD

**Issue by tringuyenduc2903** [redsquirrelstudio/laravel-backpack-export-operation#5]
## Reproduce the error
[Quay phim màn hình từ 10-04-2024 11:10:59.webm](https://github.com/redsquirrelstudio/laravel-backpack-export-operation/assets/101564593/0e00bf96-2e3a-4904-aff8-e70cafd8854f)

## How to fix
In resources/views/**configure-export.blade.php** file
```javascript
// $(document).ready(() => {
//     $("#btnIncludeAll").click(e => {
//         e.preventDefault();
//         let include_fields = document.getElementsByClassName('include-field');
//         include_fields.forEach(field => field.value = 1);
//     });
//
//     $("#btnExcludeAll").click(e => {
//         e.preventDefault();
//         let include_fields = document.getElementsByClassName('include-field');
//         include_fields.forEach(field => field.value = 0);
//     });
// })

$("#btnIncludeAll").on("click", (event) => {
    event.preventDefault();
    $(".include-field").val(1);
});

$("#btnExcludeAll").on("click", (event) => {
    event.preventDefault();
    $(".include-field").val(0);
});

```

**Comment by redsquirrelstudio** [comment]
Hi @tringuyenduc2903 

Thank you for sending this through, sorry for the delay in getting back to you!

I agree the code you've suggested is much more elegant. However, the old version was working fine on my end, 

Can I ask what browser you were using?


Many thanks!
